---
  defaults: &defaults
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    adapter: postgresql
    encoding: utf8
    database: rails_switcher_<%= Rails.env.downcase.try(:strip) %>
    username: postgres
    password:
    reconnect: false
    min_messages: warning
    pool: 45

  development:
    <<: *defaults

  test:
    <<: *defaults
    database: postgres
