---
  defaults: &defaults
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    adapter: postgresql
    encoding: utf8
    database: <%= ENV.fetch("DATABASE", "postgres") %>
    username: postgres
    password:
    reconnect: false
    min_messages: warning
    pool: 45

  development:
    <<: *defaults

  test:
    <<: *defaults
