defaults: &defaults
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  adapter: postgresql
  encoding: utf8
  database: postgres
  username: <%= ENV.fetch("POSTGRES_USER","postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD",nil) %>
  reconnect: false
  min_messages: warning
  prepared_statements: false
  port: 5432
  pool: 45
  properties:
    prepareThreshold: 0
    databaseMetadataCacheFieldsMiB: 0
  idle_timeout: 1

development:
  primary:
    <<: *defaults
